with source as (
    select * from {{ source('raw', 'orders') }}
)

select
    raw_order_row_id as order_row_id,
    {{ normalize_text('order_id') }} as order_id,
    {{ normalize_text('order_status') }} as order_status,
    {{ normalize_text('order_substatus') }} as order_substatus,
    {{ normalize_text('cancelation_return_type') }} as cancellation_return_type,
    {{ normalize_text('normal_or_pre_order') }} as order_type,
    {{ normalize_text('sku_id') }} as sku_id,
    {{ normalize_text('seller_sku') }} as seller_sku,
    {{ normalize_text('product_name') }} as product_name,
    {{ normalize_text('variation') }} as variation,
    {{ safe_bigint('quantity') }} as quantity,
    {{ safe_bigint('sku_quantity_of_return') }} as returned_quantity,
    {{ safe_numeric('sku_unit_original_price') }} as sku_unit_original_price,
    {{ safe_numeric('sku_subtotal_before_discount') }} as sku_subtotal_before_discount,
    {{ safe_numeric('sku_platform_discount') }} as sku_platform_discount,
    {{ safe_numeric('sku_seller_discount') }} as sku_seller_discount,
    {{ safe_numeric('sku_subtotal_after_discount') }} as sku_subtotal_after_discount,
    {{ safe_numeric('shipping_fee_after_discount') }} as shipping_fee_after_discount,
    {{ safe_numeric('original_shipping_fee') }} as original_shipping_fee,
    {{ safe_numeric('shipping_fee_seller_discount') }} as shipping_fee_seller_discount,
    {{ safe_numeric('shipping_fee_platform_discount') }} as shipping_fee_platform_discount,
    {{ safe_numeric('payment_platform_discount') }} as payment_platform_discount,
    {{ safe_numeric('taxes') }} as taxes,
    {{ safe_numeric('order_amount') }} as order_amount,
    {{ safe_numeric('order_refund_amount') }} as order_refund_amount,
    {{ safe_timestamp('created_time') }} as created_at,
    {{ safe_timestamp('paid_time') }} as paid_at,
    {{ safe_timestamp('rts_time') }} as ready_to_ship_at,
    {{ safe_timestamp('shipped_time') }} as shipped_at,
    {{ safe_timestamp('delivered_time') }} as delivered_at,
    {{ safe_timestamp('cancelled_time') }} as cancelled_at,
    {{ normalize_text('cancel_by') }} as cancelled_by,
    {{ normalize_text('cancel_reason') }} as cancel_reason,
    {{ normalize_text('fulfillment_type') }} as fulfillment_type,
    {{ normalize_text('warehouse_name') }} as warehouse_name,
    {{ normalize_text('delivery_option') }} as delivery_option,
    {{ normalize_text('shipping_provider_name') }} as shipping_provider_name,
    {{ normalize_text('payment_method') }} as payment_method,
    {{ safe_numeric('weight_kg') }} as weight_kg,
    {{ normalize_text('product_category') }} as product_category,
    {{ normalize_text('checked_status') }} as checked_status,
    {{ normalize_text('order_channel') }} as order_channel,
    {{ normalize_text('creator_handle') }} as creator_handle,
    {{ normalize_text('request_tax_invoice') }} as request_tax_invoice,
    _source_file as source_file,
    _source_row_number as source_row_number,
    _batch_id as batch_id,
    _file_hash as file_hash,
    _ingested_at as ingested_at,
    _pipeline_run_id as pipeline_run_id,
    _ingestion_file_id as ingestion_file_id
from source
